name = "village-payment-auth"
compatibility_date = "2025-04-03"
main = "./src/worker.ts"

compatibility_flags = ["nodejs_compat"]
assets = { directory = "./dist/client", not_found_handling = "single-page-application", run_worker_first = ["/api/*"] }


# These are for the WebAuthn Relying Party (RP) configuration.
# Development environment configuration
[vars]
RP_NAME = "Village Payment Auth"
VAPID_PUBLIC_KEY = "BJ1zmk8flcOTHoUBMnLw-OiKQ4Ykj0e67ThbzkGvoP8gYAZ7xcfX4dy_ZKXU3NQcfdCQd4Pux7QccUpcc3XHZb0"
VAPID_SUBJECT = "mailto:admin@village-payment.com"

[[d1_databases]]
binding = "DB"
database_name = "village_payments"
database_id = "d3c3d241-54ad-4a81-bf15-6556fe27c3ac"

[[d1_databases]]
binding = "DBJOURNAL"
database_name = "vpcs-journal"
database_id = "784270a8-ffe1-4115-b7fb-7d89b5eae768"

[[env.production.queues.producers]]
binding = "AUTO_APPROVAL_QUEUE"
queue = "auto-approval-queue"

[[env.production.queues.consumers]]
queue = "auto-approval-queue"
max_batch_size = 10
max_batch_timeout = 30

[env.production]
# Production environment configuration
[vars]
RP_NAME = "Village Payment Auth"
VAPID_PUBLIC_KEY = "BJ1zmk8flcOTHoUBMnLw-OiKQ4Ykj0e67ThbzkGvoP8gYAZ7xcfX4dy_ZKXU3NQcfdCQd4Pux7QccUpcc3XHZb0"
VAPID_SUBJECT = "mailto:admin@village-payment.com"

[[kv_namespaces]]
binding = "FAMILIES_KV"
id = "1562fd7cd92346d9b2d4889d7014a773" 
[[kv_namespaces]]
binding = "PENDING_KV"
id = "fcf8ddd5dd504cafaab0604235a968ed"
[[kv_namespaces]]
binding = "VENDORS_KV"
id = "61279cf83ecb41869c059068765bad0c"
