name = "village-payment-auth"
compatibility_date = "2025-04-03"
main = "./src/worker.ts"

compatibility_flags = ["nodejs_compat"]
assets = { not_found_handling = "single-page-application",run_worker_first = ["/api/*"] }


# These are for the WebAuthn Relying Party (RP) configuration.
# We'll use localhost for development.
[vars]
RP_ID = "localhost"
RP_NAME = "Village Payment Auth"
RP_ORIGIN = "http://localhost:5173"

[[d1_databases]]
binding = "DB"
database_name = "village_payments"
database_id = "8f90582f-f47c-41c3-afe2-9715b069405d"

[[d1_databases]]
binding = "DBAUTH"
database_name = "auth-db"
database_id = "db1a779b-9861-43ac-85b9-87d3c33dfadd"  # Replace with actual database ID

[[env.production.queues.producers]]
binding = "AUTO_APPROVAL_QUEUE"
queue = "auto-approval-queue"

[[env.production.queues.consumers]]
queue = "auto-approval-queue"
max_batch_size = 10
max_batch_timeout = 30

[env.production]
[[kv_namespaces]]
binding = "FAMILIES_KV"
id = "your-families-namespace-id" 
[[kv_namespaces]]
binding = "PENDING_KV"
id = "your-pending-namespace-id"
[[kv_namespaces]]
binding = "VENDORS_KV"
id = "your-vendors-namespace-id"
